### ISSUE TITLE
[github] Unable to clone the repository. The template includes files that are larger than 10 megabytes.

### ISSUE THREAD

**Issue by andrealeardini** [google/eleventy-high-performance-blog#1]
I'm following the steps suggested in the README.md file to clone the repository. 
GitHub fails to complete the operation, returns this error message:
![image](https://user-images.githubusercontent.com/25171375/92263544-15d9cd80-eedd-11ea-946c-6eff0dc79235.png)

**Comment by cramforce** [comment]
Thanks. Fixed

**Comment by 404-unf** [comment]
it's happening again

**Comment by cramforce** [comment]
I just tried and it seems to be working fine. What steps did you take?
