### ISSUE TITLE
Build errors out when the image size is above a certain size in memory during processing

### ISSUE THREAD

**Issue by indcoder** [google/eleventy-high-performance-blog#10]
If the markdown has a number of images and if an individual image is over the size that is optioned in dependency of the image processing utility

https://github.com/HackerspaceMumbai/goog11ty/issues/4

Low hanging fruit: Mention this in the Readme

The real solution would be providing a way to override the default

**Comment by MyIsaak** [comment]
`jpeg-js` (subdependency of `jimp`) has an options to solve this:
https://github.com/eugeneware/jpeg-js/blob/ca276011b6c974a5c488bc48ca0f8edb9d505069/index.d.ts#L23
However `jimp` (used in this project) doesn't allow for any access, therefore I've written an issue on their repository oliver-moran/jimp#939

**Comment by cramforce** [comment]
This probably won't be resolvable unless the option would be exposed to `sharp`

**Comment by MyIsaak** [comment]
@cramforce Agreed. It is redundant having two image processing libraries anyways. Replacing the `jimp` implementation with `sharp` means we can get rid of `jimp`. Would seem okay to me unless `jimp` has further plans of use?

**Comment by cramforce** [comment]
Yeah, seems like we should replace `jimp` with `sharp`. Right now jimp is used in the blurry-placeholder implementation. Should be relatively easy to replace.
