### ISSUE TITLE
Build failed with cloudflare pages

### ISSUE THREAD

**Issue by ornelasnarciso** [google/eleventy-high-performance-blog#106]
Hello.

The starter works perfectly fine with Netlify but wont build with cloudflare pages (as expected). 

I have no intention on storing my website on Netlify. Is there a quick fix for the starter to work with cloudflare pages? 

Thank you.

**Comment by cramforce** [comment]
I just tried it and it works fine https://eleventy-high-performance-blog-1.pages.dev/

Did you use the 11ty preset in the setup? If you you need to switch to `npm run build` as the build command instead.

**Comment by ornelasnarciso** [comment]
Totally forgot to change the build command on cloudflare. 

Everything is working just fine. Thank you. :)

**Comment by cramforce** [comment]
Great

**Comment by ornelasnarciso** [comment]
Me again, sadly. 

The other day everything was working, but now it's not. Once i put my website all together some JavaScript wont work.

I think this is structure related but since I don't have anyone to review my code I would like you to review it (if you have the time).  I've spent hours trying to make everything work and I really want to use this starter, because it's the must complete for 11ty. 

What I can't fix:

1. The CSS on _includes/layouts/post.njk If I place {% block article %} next to {{ content | safe }} my CSS wont work. If i place the {% block article %} next to {{ content | safe }} and try to use article .someclass { } it wont take any effect. Think this is related to safety issues (for the CSS to only read the article class) but I can't figure how to use this feature. 

2. The JavaScript I'm using for the social buttons work, but the back-to-top on single article and hamburger on mobile don't. Jquery not loading? Maybe related to the first issue and since the CSS is not being read the Javascript for the back-to-top and hamburger wont work?  

Thank you for your time and sorry for being here again. And I'll keep trying to figure what is wrong.  

My code: https://github.com/ornelasnarciso/ornelasnarciso11ty
