### ISSUE TITLE
Image blurring works weird with transparent PNGs

### ISSUE THREAD

**Issue by cozarkd** [google/eleventy-high-performance-blog#120]
Should the blurry placeholder disappear once the image loaded?

Result:
![Captura de pantalla 2021-12-31 a las 14 10 48](https://user-images.githubusercontent.com/6465435/147825198-eba3129e-3948-40ca-94a5-080bb8cbfb2a.png)

Expected:
![Captura de pantalla 2021-12-31 a las 14 11 13](https://user-images.githubusercontent.com/6465435/147825205-e0d66f21-ca07-474c-9bcd-cad5f344bb99.png)

**Comment by cramforce** [comment]
This line would prevent this https://github.com/google/eleventy-high-performance-blog/blob/main/src/main.js#L256
but as documented there it is racy.

I wonder what is a better way to handle images with transparency:

- Just remove the race condition
- Provide an opt-out for blurry placeholder
- Make the placeholder just fully transparent

**Comment by cozarkd** [comment]
I'm not sure that I understand the code there but I thought it had something to do with "not painting" the blurry img if the real img is loaded already. But I can see both because the real image has transparency and the blurry image goes out of the original size with the blur effect.

A way to safelist some images could work as a workaround. Something like .no-blurry. I guess that's your second option. Third seems fine too.

What do you think?

**Comment by cozarkd** [comment]
So I changed this line in img-dim.js
`  if (img.tagName == "IMG" && img.getAttribute != "noblur") {`
and seems to work fine now.

I'm not that good with js so maybe is not the best solution.

**Comment by cramforce** [comment]
Could you try this diff (please ignore the first part that is just a prettier reformat.

**Comment by cozarkd** [comment]
Nice! Works fine now.
Thanks for your work.
