### ISSUE TITLE
GA issue #46 should not be hard-coded

### ISSUE THREAD

**Issue by inetbiz** [google/eleventy-high-performance-blog#130]
https://github.com/google/eleventy-high-performance-blog/blob/3d8c2dffb395d2196eb5c4e3ce42c2312e3a8538/functions/ga.js#L77

**Comment by omair-inam** [comment]
@cramforce you've fixed this in https://github.com/google/eleventy-high-performance-blog/commit/703b81d6ad62680e2bf134a8fb43848aa806ed31 
This can probably be closed.

**Comment by cramforce** [comment]
Thanks!
