### ISSUE TITLE
Twitter Web Intents

### ISSUE THREAD

**Issue by inetbiz** [google/eleventy-high-performance-blog#134]
There are a few. What if we wanted to increase comment count and create the first tweet and grab the tweet ID? Quoted tweet and mini-profile.

https://github.com/google/eleventy-high-performance-blog/blob/d0190efdaf1aa3ac504279f453c587eb6c2e97a7/src/main.js#L30-L39

**Comment by cramforce** [comment]
Sorry, I don't understand the question, but it is probably out of scope for the template.
