### ISSUE TITLE
Tags do not function correctly

### ISSUE THREAD

**Issue by omair-inam** [google/eleventy-high-performance-blog#137]
Examples:
* https://eleventy-high-performance-blog-sample.industrialempathy.com/tags/ comes back empty:
![image](https://user-images.githubusercontent.com/3627923/173193434-3224c9cf-6c7d-487c-8f76-25c466273b55.png)

* https://eleventy-high-performance-blog-sample.industrialempathy.com/tags/second-tag/ also comes back empty even though the [fourthpost](https://github.com/omair-inam/11ty-classless-high-performance-starter/blob/main/posts/fourthpost.md) is tagged with second-tag:
![image](https://user-images.githubusercontent.com/3627923/173193476-e873d628-89e7-4166-9928-c8186ecfd5cf.png)

**Comment by omair-inam** [comment]
Can be addressed by the change in https://github.com/omair-inam/11ty-classless-high-performance-starter/issues/22

**Comment by cramforce** [comment]
Feel free to send a PR

**Comment by omair-inam** [comment]
@cramforce:
Here you go: https://github.com/google/eleventy-high-performance-blog/pull/138

For a demo:
https://deploy-preview-138--dreamy-nightingale-2f55ea.netlify.app/tags/

**Comment by cramforce** [comment]
Thanks!
