### ISSUE TITLE
Missing meta tags for images in social media cards

### ISSUE THREAD

**Issue by indcoder** [google/eleventy-high-performance-blog#14]
Social media cards for the blogs posts are a vital visual cue that invites reader to peruse the blog post. Also an image on the social media card makes it appear more "professional"

**Comment by cramforce** [comment]
I don't think these are missing, but please reopen with a specific example. See https://github.com/google/eleventy-high-performance-blog/blob/main/_includes/layouts/base.njk#L29

**Comment by indcoder** [comment]
I was thinking for those will create repos and may not have filled an image in the frontmatter. Its best there be a default and the usual practice is to have the Blog logo as the default placeholder

https://github.com/HackerspaceMumbai/goog11ty/blob/96480d3246d91d6d823c25e50edf86256725e44a/_includes/layouts/base.njk#L33

Also we are missing OG:URL meta tag which is linked to the blog post canonical/permalink.

**Comment by cramforce** [comment]
OG:URL is redundant.

**Comment by indcoder** [comment]
![image](https://user-images.githubusercontent.com/2099300/92663522-29db6000-f31f-11ea-9e2b-00306cf04e8d.png)

For most blogs, they have to keep two Gods happy, the PageRank[Search Results] and EdgeRank[SocialFeed]. 

If the template is looking to support folks to move their blogs to it, then og:url is an important parameter to ensure their blog posts don't suffer in their ranking.

Please open this issue; a PR is incoming 😁

**Comment by cramforce** [comment]
In practice they read the canonical URL instead. It would only make sense to specify `og:url` if the values would be different.
