### ISSUE TITLE
Remnant Template parameters of Eleventy Starter Blog?

### ISSUE THREAD

**Issue by indcoder** [google/eleventy-high-performance-blog#27]
@cramforce  Are these templateClass (es) defined in the repository ? Or are they remnants of the 11ty starter blog?

![image](https://user-images.githubusercontent.com/2099300/92662046-9e140480-f31b-11ea-9edb-f928705dd0cc.png)

**Comment by cramforce** [comment]
Yeah, they are remnants. It might make sense to restore the feature (just adds a class to the body element). But would also be fine to just remove these.

**Comment by indcoder** [comment]
Ok I will be removing these on  our forked repo
