### ISSUE TITLE
Cache.js is not linted?

### ISSUE THREAD

**Issue by indcoder** [google/eleventy-high-performance-blog#31]
What are the reasonings to not lint cache.js ?
![image](https://user-images.githubusercontent.com/2099300/92936347-9c575780-f467-11ea-94a0-ef8dab7ef938.png)

My query stems from the following Lighthouse advice that there is a 3x potential savings. 

![image](https://user-images.githubusercontent.com/2099300/92936069-4b476380-f467-11ea-8eff-b6ebd6c22ddf.png)

**Comment by cramforce** [comment]
It's a 1:1 copy of https://www.google-analytics.com/analytics.js

In theory the size could be reduced, but in practice this would be quite difficult and also users of the template might use a bigger feature set of GA and actually need that JS.

**Comment by cramforce** [comment]
FWIW I landed https://github.com/google/eleventy-high-performance-blog/commit/e46b53c45e8d3c8bfd129f75d0cf8f636bdaae7b yesterday to make it easy to turn this off completely, or rather make it off by default.

**Comment by indcoder** [comment]
But IMO Lighthouse audit is hinting that part of the code in cached.js is redundant i.e. DCE is not happening completely; theoretically rollup should be ideally removing any extraneous code from this file.

**Comment by cramforce** [comment]
It won't help here. The API of GA cannot be dead code eliminated as it goes through the untyped `ga` function

**Comment by indcoder** [comment]
Thank you. I was striving to get that elusive 100 % in the LightHouse perf  score😀

**Comment by cramforce** [comment]
One thing to consider would be to delay loading the GA file a bit. But that would only cheat the Lighthouse test and not actually improve UX

**Comment by indcoder** [comment]
Its all for reader's experience; Lighthouse are just indicators for that. Thank you for your time on this, I will close the issue.
