### ISSUE TITLE
Smartcrop with Sharp

### ISSUE THREAD

**Issue by headapples** [google/eleventy-high-performance-blog#37]
Do you think there is a straightforward way to include Smartcrop with Sharp to process the images? 
 
Perhaps as part of the srcset.js script?

 This is a really elegant and fantastic starter template and is exceptional work so this would be my only feature request to help with the art direction case for responsive images.

**Comment by cramforce** [comment]
It would be straightforward to add, but possibly hard to generalize (clearly not everyone wants smartcrop). On the other hand, the point of starter templates is that folks can change them, so I'm not sure any change is needed.

**Comment by headapples** [comment]
Thanks so much for the quick reply and honestly a huge hat tip for the elegance of this starter. There are so many little details in it that just make the difference with performance. They are all things that I had read about as I am very performance conscious but hadn't seen how some of them would be used together in production so really a huge thanks! (especially content visibility). 
  I'm relatively new to using node in production beyond straight forward asset processing. Could you perhaps suggest the part of the srcset.js I would have to target to include smartcrop? I would really appreciate any guidance on this. 
  
 Just to clarify why I also thought it might be a general use case: because beyond a certain level of sizing an image down you will always want to see the focus of the image, so I was thinking that below a certain size I would always apply the cropping as I think many other people would. It would almost be like setting a threshold below which you want the cropping (and the art direction) which could be a single number so even non-technical content editors could choose it. 

 I'm just really struggling to work out where best to hook into the brilliant image processing pipeline you have setup to apply Smartcrop without adversely affecting everything else.

**Comment by cramforce** [comment]
This is where `sharp` is actually called (I suppose you found that).

Typically smartcrop is applied when changing the aspect ratio of an image which this never does. You are proposing to use it more like a zoom, right? I'm not actually sure smartcrop actually does that. Another issue is that the same image asset might be used across different physical dimensions based on the screen pixel density. E.g. the 1280px asset might appear on a tiny screen with 4x dpi or on a desktop screen with 1x dpi.

**Comment by headapples** [comment]
Ah yes, I suppose it is more like a zoom. Thanks for actually taking the time to think about the use case, so many people don't listen to that part!
  You've hit the nail on the head I think. I had half considered this previously, in that I might be better off using a resized image that uses "contain" to create a pseudo crop, as long as the actual image being delivered is a small enough file size for low powered devices on poor network connections. 
  I think for most use cases this "pseudo crop" with something like "contain" should do the trick, and avoids the complexity that you point out with different dpr ratios.
