### ISSUE TITLE
Black bars on the left and right for blurry placeholder images

### ISSUE THREAD

**Issue by arjunsajeev** [google/eleventy-high-performance-blog#44]
I am not sure if this is an issue or if I'm missing something. I noticed that the blurry placeholder image on the [demo site](https://eleventy-high-performance-blog-sample.industrialempathy.com/posts/secondpost/) had black bars on the left and right sides while loading and did not match the width of the original image.  I was able to reproduce this locally as well.

**Comment by cramforce** [comment]
I'll take a look

**Comment by cramforce** [comment]
Ah, yes. This appears to be happening with that image but not in general.

**Comment by arjunsajeev** [comment]
Awesome, thank you! 🙂
