### ISSUE TITLE
absoluteURL template error

### ISSUE THREAD

**Issue by PabloC** [google/eleventy-high-performance-blog#58]
Any idea on how to fix this error related to absoluteURL?

![image](https://user-images.githubusercontent.com/764/101410234-592e4880-38df-11eb-8619-556858ae3834.png)

**Comment by cramforce** [comment]
Are you seeing this on a fresh checkout?

**Comment by PabloC** [comment]
Yes, totally fresh. I'am new to eleventy. I think this is related to the RSS Plugin which is not configured in eleventy.js, but I'am not sure.

**Comment by PabloC** [comment]
Please apologies, I did not clone the project well. Sorry.
