### ISSUE TITLE
Blurred placeholders and images with transparent background

### ISSUE THREAD

**Issue by andrealeardini** [google/eleventy-high-performance-blog#60]
Hi Malte,
Blurred placeholders are visible as a background when the image is loaded if the image has an alpha (transparency) channel.
Can they be made optional for a specific image or have them removed once the image is loaded (without affecting performance)?

Andrea

**Comment by cramforce** [comment]
Interesting. Such code is actually already in place, but right now it is best effort and basically misses load events that happen before the JS loads https://github.com/google/eleventy-high-performance-blog/blob/main/src/main.js#L235

The docs there explain why that race condition is fine for the performance use case. It would definitely be possible to remove the race condition.

**Comment by andrealeardini** [comment]
Sorry, it was my mistake. I had skipped the existing JS code. It works fine. Thank you.
