### ISSUE TITLE
Add support for web-vitals library

### ISSUE THREAD

**Issue by nickFalcone** [google/eleventy-high-performance-blog#61]
Hi @cramforce, is there any interest in adding support for the Web Vitals library? I did this on my own version of the blog and got it sending CLS, FID, and LCP to Google Analytics. My steps were:

1. Add new file `/js/web-vitals.js` containing the [UMD web vitals library](https://unpkg.com/web-vitals@1.0.1/dist/web-vitals.umd.js)
2. Reference from `base.njk` as `<script defer src="{{ "/js/web-vitals.js" | addHash }}"></script>`
3. Send to Google Analytics from `base.njk`, wrapping the [analytics.js example](https://github.com/GoogleChrome/web-vitals#using-analyticsjs) in a `<script csp-hash>` tag

I am still seeing perfect Lighthouse scores, and started getting event data ~24 hours after deploy (LCP below). Happy to open a pull request with these changes for feedback. 😃  

![lcp](https://user-images.githubusercontent.com/6636483/102149906-89289f00-3e3d-11eb-929d-e3b9b87df335.JPG)

**Comment by cramforce** [comment]
Yeah, I think that is a good idea!

**Comment by nickFalcone** [comment]
Hi @cramforce, I wanted to check and see if Web Vitals events are getting populated in GA for your site? LCP, CLS, and FID are getting reported for my site but I am guessing yours will have a larger sample size.

**Comment by cramforce** [comment]
I haven't ported the code over to my main site yet unfortunately
