### ISSUE TITLE
Slash wrong direction

### ISSUE THREAD

**Issue by jakefuller1** [google/eleventy-high-performance-blog#65]
If I try to insert local image on html blog post
`<img` src="../../img/exercise.jpg" width="750" height="427" alt="No sleep &#39;til Brooklyn" >

The slash is wrong direction in srcset /img\. It also needs ../../ ?
`<source` sizes="(max-width: 608px) 100vw, 608px" srcset="/img\exercise-1920w.avif 1920w (snip)
but ok in fallback image - note back slash and ../../
<img height="427" src="../../img/exercise.jpg" (snip)`

**Comment by cramforce** [comment]
Super weird. As far as I can see there is no place in the code-base where back-slashes are ever written to anything.

Are you on windows?

**Comment by jakefuller1** [comment]
Yes this is Win10 Pro, I'm using CMD.
However, https://github.com/google/eleventy-high-performance-blog/blob/main/posts/secondpost.md
This  doesn't work either but maybe just typo?
`![Test` Share SVG](../../img/doener.jpg)

**Comment by cramforce** [comment]
It works here https://eleventy-high-performance-blog-sample.industrialempathy.com/posts/secondpost/#test-relative-local-image

If you are on Windows, then that is likely the issue. Could try applying this PR and see if it helps? https://github.com/google/eleventy-high-performance-blog/pull/66

**Comment by jakefuller1** [comment]
OK will try,  new to 11ty ...
Works there (above link) but only fallback, notice srcset and image path differ
``<source sizes="(max-width: 608px) 100vw, 608px" srcset="/img/doener-1920w.avif 1920w
<img alt="Test Share SVG" height="1536" src="../../img/doener.jpg"

**Comment by cramforce** [comment]
Ah, I see what you mean. The legacy `src` should possibly be rewritten for consistency reasons, although both of those URLs work in practice.

**Comment by jakefuller1** [comment]
Does change things - in srcset to img/ . I would merge this #66 
However, you're correct both urls work ... in Edge, FF and chrome network tab shows it is downloading .webp not jpg, on your production url. But in 11ty server, does not show image in big 3 browsers. Perhaps it will in IIS.

Any hints how to generate both html and amp from same source posts?
Hugo had this - although it was still lot of work. (duplicate base and base.amp, etc.

Thank you for this sample for me to learn from.

**Comment by cramforce** [comment]
There is no conversion from non-AMP to AMP in this project. It just optimizes your AMP pages if you happen to generate them.
