### ISSUE TITLE
Google Analytics is not working

### ISSUE THREAD

**Issue by buoyantair** [google/eleventy-high-performance-blog#69]
Hello!! First off!,  Thank you for this wonderful wonderful blog!! I'm learning a lot from it!! Recently I have used this project as a base for a blog I was working on and I did configure the GA as expected but I am not sure why I cannot really get any stats in the GA? (There are no errors in the console too!)

Here's the website I am talking about: https://jsandfriends.dev/

**Comment by cramforce** [comment]
Hey @buoyantair,

Which host are you using for your blog?

The default GA implementation is proxying requests to avoid cross-origin requests. This is implemented as a netlify function here https://github.com/google/eleventy-high-performance-blog/blob/main/functions/ga.js
It would be easy to port to other backends. Or you replace the provided analytics script with Google's default one which would avoid the proxy.

**Comment by buoyantair** [comment]
Hello @cramforce I am using the default settings, with everything deployed on Netlify

**Comment by cramforce** [comment]
Ah, sorry, I didn't click though.

Yeah, it seems to make the right requests without failure. Could you ensure that your GA ID is the right one? `G-DY1P50J9E8` It doesn't quite look right, but maybe the format has changed recently.

Otherwise you may need to add logging to the netlify function to see if there are any error messages being produced.

**Comment by cramforce** [comment]
Maybe see if you can find this log statement in the netlify log https://github.com/google/eleventy-high-performance-blog/blob/main/functions/ga.js#L62

**Comment by buoyantair** [comment]
This is what Google Analytics has given me as the tracking ID.... 
![image](https://user-images.githubusercontent.com/5159834/104797817-0e112a80-57e7-11eb-8baf-45735efe9ff2.png)

And according to netlify logs atleast, all I see is that the request is being proxied to google? but I am not sure why the dashboard doesnt show anything.

```
10:09:18 AM: 2021-01-16T04:39:18.615Z	4127a42f-f4ae-4925-a347-58a1575b5d03	INFO	Received POST request from, origin: https://jsandfriends.dev
10:09:18 AM: 2021-01-16T04:39:18.617Z	4127a42f-f4ae-4925-a347-58a1575b5d03	INFO	proxying params: v, _v, a, t, _s, dl, dr, ul, de, dt, sd, sr, vp, je, _u, jid, gjid, cid, tid, _gid, _r, z, uip, ua
10:09:18 AM: Duration: 61.90 ms	Memory Usage: 70 MB	Init Duration: 142.61 ms	
10:09:26 AM: 2021-01-16T04:39:26.133Z	85c7df52-5b7b-4710-9656-3cb2b16c664e	INFO	Received POST request from, origin: https://jsandfriends.dev
10:09:26 AM: 2021-01-16T04:39:26.134Z	85c7df52-5b7b-4710-9656-3cb2b16c664e	INFO	proxying params: v, _v, a, t, _s, dl, dr, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:09:26 AM: Duration: 20.01 ms	Memory Usage: 71 MB	
10:10:21 AM: 2021-01-16T04:40:21.741Z	a66a1aa3-1e71-48a3-8f91-db5e773c78c0	INFO	Received POST request from, origin: https://jsandfriends.dev
10:10:21 AM: 2021-01-16T04:40:21.741Z	a66a1aa3-1e71-48a3-8f91-db5e773c78c0	INFO	proxying params: v, _v, a, t, _s, dl, dr, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, _r, z, uip, ua
10:10:21 AM: Duration: 21.27 ms	Memory Usage: 71 MB	
10:10:22 AM: 2021-01-16T04:40:22.170Z	2273f162-b5ed-4a67-bc6e-bd4c7668e534	INFO	Received POST request from, origin: https://jsandfriends.dev
10:10:22 AM: 2021-01-16T04:40:22.171Z	2273f162-b5ed-4a67-bc6e-bd4c7668e534	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:10:22 AM: Duration: 18.38 ms	Memory Usage: 71 MB	
10:10:25 AM: 2021-01-16T04:40:25.166Z	0465e8b6-1133-45b1-966f-62ff235541f9	INFO	Received POST request from, origin: https://jsandfriends.dev
10:10:25 AM: 2021-01-16T04:40:25.167Z	0465e8b6-1133-45b1-966f-62ff235541f9	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:10:25 AM: Duration: 17.82 ms	Memory Usage: 71 MB	
10:19:52 AM: 2021-01-16T04:49:52.462Z	9ff17047-f8be-48cd-af67-bc6d1f4b19bb	INFO	Received POST request from, origin: https://jsandfriends.dev
10:19:52 AM: 2021-01-16T04:49:52.463Z	9ff17047-f8be-48cd-af67-bc6d1f4b19bb	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, _u, jid, gjid, cid, tid, _gid, _r, z, uip, ua
10:19:52 AM: Duration: 56.35 ms	Memory Usage: 70 MB	Init Duration: 150.87 ms	
10:19:52 AM: 2021-01-16T04:49:52.607Z	be3abc81-3905-4844-820e-e49bbb9d7f99	INFO	Received POST request from, origin: https://jsandfriends.dev
10:19:52 AM: 2021-01-16T04:49:52.608Z	be3abc81-3905-4844-820e-e49bbb9d7f99	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:19:52 AM: Duration: 28.31 ms	Memory Usage: 71 MB	
10:19:52 AM: 2021-01-16T04:49:52.662Z	deb78064-e7d2-4fc4-b155-1ed1b72f3bd0	INFO	Received POST request from, origin: https://jsandfriends.dev
10:19:52 AM: 2021-01-16T04:49:52.662Z	deb78064-e7d2-4fc4-b155-1ed1b72f3bd0	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:19:52 AM: Duration: 18.77 ms	Memory Usage: 71 MB	
10:19:52 AM: 2021-01-16T04:49:52.717Z	32de4f9c-5ce0-4eb3-84b0-c76ad000b15c	INFO	Received POST request from, origin: https://jsandfriends.dev
10:19:52 AM: 2021-01-16T04:49:52.717Z	32de4f9c-5ce0-4eb3-84b0-c76ad000b15c	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:19:52 AM: Duration: 18.27 ms	Memory Usage: 71 MB	
10:19:52 AM: 2021-01-16T04:49:52.838Z	dc639f85-4625-450f-9540-e0ebd761b914	INFO	Received POST request from, origin: https://jsandfriends.dev
10:19:52 AM: 2021-01-16T04:49:52.839Z	dc639f85-4625-450f-9540-e0ebd761b914	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:19:52 AM: Duration: 18.43 ms	Memory Usage: 71 MB	
10:19:53 AM: 2021-01-16T04:49:53.022Z	15c41c42-3446-48f3-b593-c1096cdb23ca	INFO	Received POST request from, origin: https://jsandfriends.dev
10:19:53 AM: 2021-01-16T04:49:53.023Z	15c41c42-3446-48f3-b593-c1096cdb23ca	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:19:53 AM: Duration: 22.88 ms	Memory Usage: 71 MB	
10:19:55 AM: 2021-01-16T04:49:55.290Z	71f5ae1c-469b-4b6e-8477-373669dcd2bb	INFO	Received POST request from, origin: https://jsandfriends.dev
10:19:55 AM: 2021-01-16T04:49:55.291Z	71f5ae1c-469b-4b6e-8477-373669dcd2bb	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:19:55 AM: Duration: 18.65 ms	Memory Usage: 71 MB	
10:20:03 AM: 2021-01-16T04:50:03.985Z	ab7b9b7b-7328-47ad-b40a-13bb5c0297d9	INFO	Received POST request from, origin: https://jsandfriends.dev
10:20:03 AM: 2021-01-16T04:50:03.985Z	ab7b9b7b-7328-47ad-b40a-13bb5c0297d9	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:20:04 AM: Duration: 25.82 ms	Memory Usage: 71 MB	
10:20:05 AM: 2021-01-16T04:50:05.909Z	20062600-7d70-414f-bd88-692de40c5616	INFO	Received POST request from, origin: https://jsandfriends.dev
10:20:05 AM: 2021-01-16T04:50:05.910Z	20062600-7d70-414f-bd88-692de40c5616	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:20:05 AM: Duration: 18.43 ms	Memory Usage: 72 MB	
10:20:44 AM: 2021-01-16T04:50:44.800Z	6faf73f1-2806-4b09-be8c-0f6539344652	INFO	Received POST request from, origin: https://jsandfriends.dev
10:20:44 AM: 2021-01-16T04:50:44.800Z	6faf73f1-2806-4b09-be8c-0f6539344652	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:20:44 AM: 2021-01-16T04:50:44.802Z	69f25d58-4910-424b-a8a6-0ad90bf526ea	INFO	Received POST request from, origin: https://jsandfriends.dev
10:20:44 AM: 2021-01-16T04:50:44.804Z	69f25d58-4910-424b-a8a6-0ad90bf526ea	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:20:44 AM: Duration: 18.86 ms	Memory Usage: 72 MB	
10:20:44 AM: Duration: 71.32 ms	Memory Usage: 70 MB	Init Duration: 148.37 ms	
10:20:51 AM: 2021-01-16T04:50:51.163Z	61f38462-eead-422d-b5b3-3eed637cf99a	INFO	Received POST request from, origin: https://jsandfriends.dev
10:20:51 AM: 2021-01-16T04:50:51.164Z	61f38462-eead-422d-b5b3-3eed637cf99a	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:20:51 AM: Duration: 25.70 ms	Memory Usage: 71 MB	
10:26:54 AM: 2021-01-16T04:56:54.772Z	f33b3cf0-d202-4b71-9077-0ae85b122301	INFO	Received POST request from, origin: https://jsandfriends.dev
10:26:54 AM: 2021-01-16T04:56:54.772Z	f33b3cf0-d202-4b71-9077-0ae85b122301	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, _u, jid, gjid, cid, tid, _gid, _r, z, uip, ua
10:26:54 AM: Duration: 18.93 ms	Memory Usage: 71 MB	
10:27:38 AM: 2021-01-16T04:57:38.018Z	6c528d45-b28f-4576-b160-e7ffe7e3566d	INFO	Received POST request from, origin: https://jsandfriends.dev
10:27:38 AM: 2021-01-16T04:57:38.018Z	6c528d45-b28f-4576-b160-e7ffe7e3566d	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:27:38 AM: Duration: 17.27 ms	Memory Usage: 71 MB	
10:29:20 AM: 2021-01-16T04:59:20.059Z	625aeec9-3bd5-47bf-b879-cf5484493fbb	INFO	Received POST request from, origin: https://jsandfriends.dev
10:29:20 AM: 2021-01-16T04:59:20.059Z	625aeec9-3bd5-47bf-b879-cf5484493fbb	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:29:20 AM: 2021-01-16T04:59:20.059Z	4129bba0-ae2a-46c3-a886-3860079961a7	INFO	Received POST request from, origin: https://jsandfriends.dev
10:29:20 AM: 2021-01-16T04:59:20.060Z	4129bba0-ae2a-46c3-a886-3860079961a7	INFO	proxying params: v, _v, a, t, ni, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, ev, _u, jid, gjid, cid, tid, _gid, _r, z, uip, ua
10:29:20 AM: Duration: 18.03 ms	Memory Usage: 71 MB	
10:29:20 AM: Duration: 20.08 ms	Memory Usage: 72 MB	
10:29:20 AM: 2021-01-16T04:59:20.081Z	0b1b5820-0d2b-4384-bacf-5f70c3849f53	INFO	Received POST request from, origin: https://jsandfriends.dev
10:29:20 AM: 2021-01-16T04:59:20.082Z	0b1b5820-0d2b-4384-bacf-5f70c3849f53	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:29:20 AM: Duration: 18.03 ms	Memory Usage: 71 MB	
10:33:16 AM: 2021-01-16T05:03:16.255Z	41f466ba-4c01-4ed1-b33e-cb1f53670bee	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:16 AM: 2021-01-16T05:03:16.255Z	41f466ba-4c01-4ed1-b33e-cb1f53670bee	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, _r, z, uip, ua
10:33:16 AM: Duration: 17.70 ms	Memory Usage: 71 MB	
10:33:18 AM: 2021-01-16T05:03:18.191Z	0b258aa8-d2b9-4210-b76d-ebacbb739181	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:18 AM: 2021-01-16T05:03:18.191Z	0b258aa8-d2b9-4210-b76d-ebacbb739181	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:18 AM: Duration: 16.92 ms	Memory Usage: 72 MB	
10:33:21 AM: 2021-01-16T05:03:21.915Z	48dd1835-c7a2-4c6c-acca-d57c939566c5	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:21 AM: 2021-01-16T05:03:21.916Z	48dd1835-c7a2-4c6c-acca-d57c939566c5	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:21 AM: Duration: 16.81 ms	Memory Usage: 72 MB	
10:33:24 AM: 2021-01-16T05:03:24.139Z	1eb100ec-6d8c-4f74-a086-01d9e33e67de	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:24 AM: 2021-01-16T05:03:24.140Z	1eb100ec-6d8c-4f74-a086-01d9e33e67de	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:24 AM: Duration: 16.80 ms	Memory Usage: 72 MB	
10:33:25 AM: 2021-01-16T05:03:25.859Z	11bfe993-a987-4e51-886b-fae7f29cc0ee	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:25 AM: 2021-01-16T05:03:25.859Z	11bfe993-a987-4e51-886b-fae7f29cc0ee	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:25 AM: Duration: 17.84 ms	Memory Usage: 72 MB	
10:33:27 AM: 2021-01-16T05:03:27.824Z	0bf5002a-d4ee-4f61-8672-ada0929ac6fc	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:27 AM: 2021-01-16T05:03:27.824Z	0bf5002a-d4ee-4f61-8672-ada0929ac6fc	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:27 AM: Duration: 16.08 ms	Memory Usage: 72 MB	
10:33:29 AM: 2021-01-16T05:03:29.828Z	533ffb61-094c-423b-95ef-0d1569699660	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:29 AM: 2021-01-16T05:03:29.829Z	533ffb61-094c-423b-95ef-0d1569699660	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:29 AM: Duration: 17.55 ms	Memory Usage: 72 MB	
10:33:36 AM: 2021-01-16T05:03:36.714Z	6a19a3a1-7003-4e6c-b236-cee14a97833c	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:36 AM: 2021-01-16T05:03:36.715Z	6a19a3a1-7003-4e6c-b236-cee14a97833c	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:36 AM: Duration: 16.62 ms	Memory Usage: 72 MB	
10:33:38 AM: 2021-01-16T05:03:38.760Z	65432571-20bf-4203-a19a-705416b64ab2	INFO	Received POST request from, origin: https://jsandfriends.dev
10:33:38 AM: 2021-01-16T05:03:38.766Z	65432571-20bf-4203-a19a-705416b64ab2	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:33:38 AM: Duration: 22.93 ms	Memory Usage: 76 MB	
10:34:33 AM: 2021-01-16T05:04:33.395Z	34ed585f-2b0e-4ac4-ba25-d5abe6e6507b	INFO	Received POST request from, origin: https://jsandfriends.dev
10:34:33 AM: 2021-01-16T05:04:33.396Z	34ed585f-2b0e-4ac4-ba25-d5abe6e6507b	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, _r, z, uip, ua
10:34:33 AM: Duration: 18.83 ms	Memory Usage: 76 MB	
10:34:36 AM: 2021-01-16T05:04:36.394Z	a37124c4-0b5a-4919-926c-b076587228e4	INFO	Received POST request from, origin: https://jsandfriends.dev
10:34:36 AM: 2021-01-16T05:04:36.394Z	a37124c4-0b5a-4919-926c-b076587228e4	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:34:36 AM: Duration: 17.31 ms	Memory Usage: 76 MB	
10:34:37 AM: 2021-01-16T05:04:37.655Z	d69d1471-2977-4a3d-bdd6-0b0bc512933c	INFO	Received POST request from, origin: https://jsandfriends.dev
10:34:37 AM: 2021-01-16T05:04:37.656Z	d69d1471-2977-4a3d-bdd6-0b0bc512933c	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:34:37 AM: Duration: 17.65 ms	Memory Usage: 76 MB	
10:34:57 AM: 2021-01-16T05:04:57.093Z	564739a1-25d6-4f08-872b-3446f0ab4879	INFO	Received POST request from, origin: https://jsandfriends.dev
10:34:57 AM: 2021-01-16T05:04:57.094Z	564739a1-25d6-4f08-872b-3446f0ab4879	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:34:57 AM: Duration: 15.91 ms	Memory Usage: 76 MB	
10:35:08 AM: 2021-01-16T05:05:08.844Z	97fa0fa5-015a-4da7-aa3c-19c15b9a1668	INFO	Received POST request from, origin: https://jsandfriends.dev
10:35:08 AM: 2021-01-16T05:05:08.844Z	97fa0fa5-015a-4da7-aa3c-19c15b9a1668	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:35:08 AM: Duration: 16.06 ms	Memory Usage: 76 MB	
10:35:12 AM: 2021-01-16T05:05:12.275Z	2e62ddf3-e4ab-4427-b180-b0e560e0c3f9	INFO	Received POST request from, origin: https://jsandfriends.dev
10:35:12 AM: 2021-01-16T05:05:12.276Z	2e62ddf3-e4ab-4427-b180-b0e560e0c3f9	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:35:12 AM: Duration: 16.21 ms	Memory Usage: 76 MB	
10:35:17 AM: 2021-01-16T05:05:17.090Z	75ea547f-92dc-4023-9b85-8c02ef08e6e9	INFO	Received POST request from, origin: https://jsandfriends.dev
10:35:17 AM: 2021-01-16T05:05:17.091Z	75ea547f-92dc-4023-9b85-8c02ef08e6e9	INFO	proxying params: v, _v, a, t, _s, dl, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:35:17 AM: Duration: 16.23 ms	Memory Usage: 76 MB	
10:37:48 AM: 2021-01-16T05:07:48.837Z	f9803993-ad1d-4757-b743-c7d812382d3c	INFO	Received GET request from, origin: 
10:37:48 AM: 2021-01-16T05:07:48.870Z	f9803993-ad1d-4757-b743-c7d812382d3c	INFO	proxying params: _s, _v, de, dh, dp, dr, dt, t, tid, ul, v, uip, ua, cid
10:37:48 AM: Duration: 51.01 ms	Memory Usage: 83 MB	
10:37:53 AM: 2021-01-16T05:07:53.831Z	af1c347b-298f-45f6-942c-63aded930712	INFO	Received GET request from, origin: 
10:37:53 AM: 2021-01-16T05:07:53.832Z	af1c347b-298f-45f6-942c-63aded930712	INFO	proxying params: _s, _v, de, dh, dp, dr, dt, t, tid, ul, v, uip, ua, cid
10:37:53 AM: Duration: 15.83 ms	Memory Usage: 83 MB	
10:37:58 AM: 2021-01-16T05:07:58.306Z	0c6a3f17-44db-48ad-88f1-72b50e3f0e41	INFO	Received GET request from, origin: 
10:37:58 AM: 2021-01-16T05:07:58.307Z	0c6a3f17-44db-48ad-88f1-72b50e3f0e41	INFO	proxying params: _s, _v, de, dh, dp, dr, dt, t, tid, ul, v, uip, ua, cid
10:37:58 AM: Duration: 18.29 ms	Memory Usage: 83 MB	
10:37:59 AM: 2021-01-16T05:07:59.815Z	90fce9f5-22cb-4cef-8723-12e0d5d1b006	INFO	Received GET request from, origin: 
10:37:59 AM: 2021-01-16T05:07:59.817Z	90fce9f5-22cb-4cef-8723-12e0d5d1b006	INFO	proxying params: _s, _v, de, dh, dp, dr, dt, t, tid, ul, v, uip, ua, cid
10:37:59 AM: Duration: 19.19 ms	Memory Usage: 83 MB	
10:39:36 AM: 2021-01-16T05:09:36.515Z	c04dc844-c63d-4f93-b5f1-d528e79a0e05	INFO	Received POST request from, origin: https://jsandfriends.dev
10:39:36 AM: 2021-01-16T05:09:36.515Z	c04dc844-c63d-4f93-b5f1-d528e79a0e05	INFO	proxying params: v, _v, a, t, _s, dl, dr, ul, de, dt, sd, sr, vp, je, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:39:36 AM: Duration: 16.99 ms	Memory Usage: 83 MB	
10:39:42 AM: 2021-01-16T05:09:42.861Z	18903005-5a03-4d29-a1e3-faf226bb9a00	INFO	Received POST request from, origin: https://jsandfriends.dev
10:39:42 AM: 2021-01-16T05:09:42.862Z	18903005-5a03-4d29-a1e3-faf226bb9a00	INFO	proxying params: v, _v, a, t, _s, dl, dr, ul, de, dt, sd, sr, vp, je, ec, ea, el, _u, jid, gjid, cid, tid, _gid, z, uip, ua
10:39:42 AM: Duration: 16.52 ms	Memory Usage: 83 MB	
```

**Comment by cramforce** [comment]
Yeah, that looks good. When you generate a JavaScript embed code are you
getting exactly the same ID?

**Comment by buoyantair** [comment]
Here's what I am getting in the html files generated in the `_site` folder. All of them have gid set in the html tag. 

![image](https://user-images.githubusercontent.com/5159834/104833838-c3b0ac00-58c1-11eb-93d2-0e3a393fa15f.png)

**Comment by cramforce** [comment]
What I mean is the track generated by Google Analytics. Should look something like this.
<img width="1191" alt="Screen Shot 2021-01-17 at 8 03 26" src="https://user-images.githubusercontent.com/89679/104848579-84229980-589a-11eb-9d6a-e99d263b17cd.png">

**Comment by KrishnaRPatel** [comment]
@buoyantair The function is expecting a `Universal Analytics` (`UA`) code, but you're using the new `Google Analytics 4` (GA) Code. Follow the instructions at the link below to get a UA code instead.

https://support.google.com/analytics/answer/10269537?hl=en

**Comment by tonihintikka** [comment]
I get also build failed when I add my own Google Analytics UA-code to metadata. When I take it off build success.
` eleventy-high-performance-blog git:(main) npm run build              

> eleventy-high-performance-blog@5.0.2 build
> npm run js-build && eleventy && npm run test


> eleventy-high-performance-blog@5.0.2 js-build
> rollup -c rollup.config.js


src/main.js → js/min.js...
created js/min.js in 359ms
Writing _site/favicon.svg from ./favicon.svg.njk.
Writing _site/sitemap.xml from ./sitemap.xml.njk.
Writing _site/feed/feed.xml from ./feed/feed.njk.
Writing _site/feed/feed.json from ./feed/json.njk.
Writing _site/feed/.htaccess from ./feed/htaccess.njk.
Writing _site/admin/index.html from ./admin/index.html.
Writing _site/posts/index.html from ./archive.njk.
Writing _site/about/index.html from ./about/index.md.
Writing _site/page-list/index.html from ./page-list.njk.
Writing _site/404.html from ./404.md.
Writing _site/index.html from ./index.njk.
Writing _site/tags/index.html from ./tags-list.njk.
Writing _site/tags/another-tag/index.html from ./tags.njk.
Writing _site/posts/Data modeling/index.html from ./posts/Data modeling.md.
Writing _site/posts/here-we-go-again/index.html from ./posts/here-we-go-again.md.
Writing _site/posts/starting-studies/index.html from ./posts/starting-studies.md.
Writing _site/posts/first-week-jamstack-with-eleventy/index.html from ./posts/first-week-jamstack-with-eleventy.md.
Writing _site/posts/who-is-fullstack-developer/index.html from ./posts/who-is-fullstack-developer.md.
Writing _site/tags/studies/index.html from ./tags.njk.
Copied 87 files / Wrote 19 files in 2.28 seconds (120.0ms each, v0.11.0)

> eleventy-high-performance-blog@5.0.2 test
> mocha test/test*.js



  check build output for a generic post
    sample post
      ✓ should have metadata
      ✓ should have inlined css
      1) should have script elements
      2) should have GA a setup
      ✓ should have a good CSP
      ✓ should have accessible buttons
      ✓ should have a share widget
      ✓ should have a header
      ✓ should have a published date
      ✓ should link to twitter with noopener
      body
        ✓ should have images
        ✓ should have json-ld
        ✓ should have paragraphs

  check build output for homepage
    homepage
      ✓ should have a top navigation
      ✓ should have a list of posts


  13 passing (157ms)
  2 failing

  1) check build output for a generic post
       sample post
         should have script elements:
     Error: expected { '0': <script async="" defer="" src="/js/min.js?hash=c372ec6a84"></script> } to have a length of 2 but got 1
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.length (node_modules/expect.js/index.js:345:10)
      at Context.<anonymous> (test/test-generic-post.js:67:31)
      at processImmediate (node:internal/timers:463:21)

  2) check build output for a generic post
       sample post
         should have GA a setup:
     TypeError: Cannot read property 'getAttribute' of undefined
      at Context.<anonymous> (test/test-generic-post.js:78:25)
      at processImmediate (node:internal/timers:463:21)



npm ERR! code 2
npm ERR! path /Users/tonihintikka/Documents/projektit/tonisblog/eleventy-high-performance-blog
npm ERR! command failed
npm ERR! command sh -c mocha test/test*.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tonihintikka/.npm/_logs/2021-01-30T12_25_47_123Z-debug.log
npm ERR! code 2
npm ERR! path /Users/tonihintikka/Documents/projektit/tonisblog/eleventy-high-performance-blog
npm ERR! command failed
npm ERR! command sh -c npm run js-build && eleventy && npm run test

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tonihintikka/.npm/_logs/2021-01-30T12_25_47_175Z-debug.log
➜  eleventy-high-performance-blog git:(main) git add .
➜  eleventy-high-performance-blog git:(main) ✗ git commit -m"google removed"
[main d2b91f4] google removed
 1 file changed, 1 insertion(+), 1 deletion(-)
➜  eleventy-high-performance-blog git:(main) npm run build                

> eleventy-high-performance-blog@5.0.2 build
> npm run js-build && eleventy && npm run test


> eleventy-high-performance-blog@5.0.2 js-build
> rollup -c rollup.config.js


src/main.js → js/min.js...
created js/min.js in 312ms
Writing _site/favicon.svg from ./favicon.svg.njk.
Writing _site/sitemap.xml from ./sitemap.xml.njk.
Writing _site/feed/feed.xml from ./feed/feed.njk.
Writing _site/feed/.htaccess from ./feed/htaccess.njk.
Writing _site/feed/feed.json from ./feed/json.njk.
Writing _site/admin/index.html from ./admin/index.html.
Writing _site/about/index.html from ./about/index.md.
Writing _site/tags/index.html from ./tags-list.njk.
Writing _site/tags/studies/index.html from ./tags.njk.
Writing _site/posts/index.html from ./archive.njk.
Writing _site/page-list/index.html from ./page-list.njk.
Writing _site/index.html from ./index.njk.
Writing _site/404.html from ./404.md.
Writing _site/posts/here-we-go-again/index.html from ./posts/here-we-go-again.md.
Writing _site/posts/Data modeling/index.html from ./posts/Data modeling.md.
Writing _site/tags/another-tag/index.html from ./tags.njk.
Writing _site/posts/who-is-fullstack-developer/index.html from ./posts/who-is-fullstack-developer.md.
Writing _site/posts/first-week-jamstack-with-eleventy/index.html from ./posts/first-week-jamstack-with-eleventy.md.
Writing _site/posts/starting-studies/index.html from ./posts/starting-studies.md.
Copied 87 files / Wrote 19 files in 2.45 seconds (128.9ms each, v0.11.0)

> eleventy-high-performance-blog@5.0.2 test
> mocha test/test*.js



  check build output for a generic post
    sample post
      ✓ should have metadata
      ✓ should have inlined css
      ✓ should have script elements
      ✓ should have GA a setup
      ✓ should have a good CSP
      ✓ should have accessible buttons
      ✓ should have a share widget
      ✓ should have a header
      ✓ should have a published date
      ✓ should link to twitter with noopener
      body
        ✓ should have images
        ✓ should have json-ld
        ✓ should have paragraphs

  check build output for homepage
    homepage
      ✓ should have a top navigation
      ✓ should have a list of posts


  15 passing (150ms)`

**Comment by cramforce** [comment]
@tonihintikka You should probably file a new issue. You made a change and the test failed. You probably just need to update the test to test what you'd like to be the correct behavior.

**Comment by tonihintikka** [comment]
> @tonihintikka You should probably file a new issue. You made a change and the test failed. You probably just need to update the test to test what you'd like to be the correct behavior.

Thanks a lot! I've got it. If I just put that original post to folder it works.

**Comment by buoyantair** [comment]
Maybe we could have support for the new GA analytics code, that would be helpful and also more importantly some sort of clarification somewhere that we only support the UA version of the GA measurement code.

**Comment by cramforce** [comment]
Clarification is a good idea. I'll have to look into whether adding support is possible with the self-hosted approach.
