### ISSUE TITLE
Font rendering after hard refresh

### ISSUE THREAD

**Issue by ap3d** [google/eleventy-high-performance-blog#71]
When I perform a hard refresh for e.g https://www.industrialempathy.com/ in Chrome (v 88.0.4324.146 ) - the Inter UI font is not rendered, but Helvetica instead. In Firefox (v 85.0) it seems to happen but less often. When I remove the font-display optional snippet in optimize-html.js, it's solved.

**Comment by cramforce** [comment]
Yep, that is what font-display optional does.

If you don't like it you can remove it in your fork, but be aware of the CLS consequences.

**Comment by ap3d** [comment]
Aha I see, thanks for getting back to me - really appreciate it.

Font-display optional - does that never render the Inter UI font the first time? Cause when I setup a fresh template of eleventy-high-performance-blog and deploy it to firebase, the first time I open the staging in Chrome or Firefox I don't get to see Inter UI.

**Comment by cramforce** [comment]
There is a very short time frame within `font-display: optional` to show the custom font when it isn't present in cache. Basically that means that you only get the font on first load with very fast / low latency internet connections.

**Comment by ap3d** [comment]
Okay clear - thank you!
