### ISSUE TITLE
Potential secret identified by GitGuardian

### ISSUE THREAD

**Issue by jazwiecki** [google/eleventy-high-performance-blog#73]
In [`js/cached.js`](https://github.com/google/eleventy-high-performance-blog/blob/22922aa589cb15cc31700d98ef3d28063677dff0/js/cached.js#L32), GitGuardian found a key when I cloned this repo:

```
(c||"https://ampcid.google.com/v1/publisher:getClientId")+"?key=<removed>"
```

I'm not sure if this is a problem for whoever owns this key, or other people who copy this repo, but I figured it was better to open an issue than ignore it. Apologies if this is a nuisance; I didn't see any existing issues which mentioned this.

**Comment by cramforce** [comment]
This isn't a problem. This is a proprietary, but globally cached and publicly available piece of software.
