### ISSUE TITLE
gif and mp4 not playing/showing up

### ISSUE THREAD

**Issue by Ben1980** [google/eleventy-high-performance-blog#75]
First of all, thanks for the really nice template. Unfortunately, I got problems shipping gifs and mp4.
I'm new to eleventy and have problems here. The gif is not playing and the mp4 not showing up at all.
https://thoughts-on-coding.netlify.app/2020/04/20/a-c++-github-template-repository-utilizing-circleci-cmake-docker-and-doxygen/

```
![Example job invocation of the CircleCI CLI](/img/circlecicli.gif)
```

```
![Example of a docker image generation for the cpptemplate](/img/cpptemplateimage.mp4)
```

**Comment by cramforce** [comment]
The GIF handling is a bug I think.

For the MP4: I don't think this is expected to work like that in markdown, is it? For now I'd use a `<video>` element for that.

**Comment by Ben1980** [comment]
> The GIF handling is a bug I think.

How can I help with the bug?

**Comment by cramforce** [comment]
The short term fix would be to skip these lines if the image is a GIF https://github.com/google/eleventy-high-performance-blog/blob/main/_11ty/img-dim.js#L72-L89

The better fix would be to transcode GIFs to videos and play them as `<video autoplay loop muted>`.

**Comment by Ben1980** [comment]
Why you think it would be better to convert the gifs into videos?
I personally thought having small gifs would be preferable compared to larger videos.

**Comment by cramforce** [comment]
No, GIFs are actually drastically larger than the same GIF transcoded to a video (Roughly 10:1 ratio).
