### ISSUE TITLE
Cookie banner

### ISSUE THREAD

**Issue by Ben1980** [google/eleventy-high-performance-blog#78]
How about a cookie banner? Wouldn't that be necessary for a blog using Google analytics?

**Comment by cramforce** [comment]
This isn't a good place for discussing whether "a cookie banner is necessary". You may want to ask your friendly lawyer friend.

The Google Analytics integration supported here is:

- Optional
- And only makes 1st party requests (as opposed to standard GA which talks directly to Google)
- Which is enforced through a strong CSP
- And respectively it can only use 1st party cookies
