### ISSUE TITLE
Fall back image

### ISSUE THREAD

**Issue by jakefuller1** [google/eleventy-high-performance-blog#81]
If you use a large image (6000 x 4000), the 'const widths' does optimize images into smaller sizes and various formats.
However, the large image is used for fall back image (img src="too-large-image.jpg). This not ideal. Starting with small image and upscaling, not ideal.
Is there a way to use the smallest or second smallest 'constant widths' to generate the fall back image?
if (img.tagName == "IMG") in img-dim.js
Could I use img.getattribute("src") and then change image.jpg to image-608w.jpg? with img.setattribute("src")
Or is there a better way?

**Comment by cramforce** [comment]
Why do you say that using the large image as fallback isn't ideal?

**Comment by jakefuller1** [comment]
The optimized images are 3K to 68K in size - 335 to 2010px wide. The fall back is 273K in size, 5184px wide. But "contain" will limit width but not file size. Original file size is 1734K.
Fallback probably shown by older browsers with slow internet? 1 to 2% of users?
2010px is 3x 670px - very high end mobile?
If fallback was -670w.jpg it would be 15K, instead of 273K
