### ISSUE TITLE
The optimized images are 3K to 68K in size - 335 to 2010px wide. The fall back is 273K in size, 5184px wide. But "contain" will limit width but not file size. Original file size is 1734K.

### ISSUE THREAD

**Issue by sernavae24** [google/eleventy-high-performance-blog#82]
The optimized images are 3K to 68K in size - 335 to 2010px wide. The fall back is 273K in size, 5184px wide. But "contain" will limit width but not file size. Original file size is 1734K.
Fallback probably shown by older browsers with slow internet? 1 to 2% of users?
2010px is 3x 670px - very high end mobile?
If fallback was -670w.jpg it would be 15K, instead of 273K

_Originally posted by @jakefuller1 in https://github.com/google/eleventy-high-performance-blog/issues/81#issuecomment-830952053_

**Comment by cramforce** [comment]
Closing as dupe
