### ISSUE TITLE
Hasha

### ISSUE THREAD

**Issue by jakefuller1** [google/eleventy-high-performance-blog#87]
Am I not understanding hash?
You hash files
  callback(null, `${absolutePath}?hash=${hash.substr(0, 10)}`);
page source
  link href="/img/favicon/favicon-192x192.png?hash=2089033c93" rel="icon" type="image/png"
  script async="" defer="" src="/js/min.js?hash=c372ec6a84"></script
files in _site
  min.js (no hash)
  favicon-192x192.png (no hash)
Shouldn't hash be appended to file name to upload to server?
BTW, js hash is sha512 (fist 10 digits) but .png is unknown?
sha512 would be 062F6715E3 not 2089033c93 (probably does not matter?)

**Comment by cramforce** [comment]
Changing file names of resources is pretty awkward in 11ty. Hence the has is added to the query string.

I don't understand whether you have a question.

**Comment by kimberlynete** [comment]
i want to delete my instagram mrs nobody now.  no longer come in the proviel.

Von meinem iPhone gesendet

> Am 28.06.2021 um 11:55 schrieb Malte Ubl ***@***.***>:
> 
> Changing file names of resources is pretty awkward in 11ty. Hence the has is added to the query string.
> 
> I don't understand whether you have a question.

**Comment by jakefuller1** [comment]
Shouldn't the hash query string be appended to file name in _site folder, to upload to server?

**Comment by cramforce** [comment]
Like I said, this is hard to do in 11ty and it doesn't really matter. The query string forces cache invalidation when the content changes. The only downside this scheme has is that you cannot deploy multiple releases concurrently.

**Comment by jakefuller1** [comment]
Thank you for clarifying 'cache invalidation'.
