### ISSUE TITLE
cant find tags in the blog or home page

### ISSUE THREAD

**Issue by gramythedj** [google/eleventy-high-performance-blog#89]
though we can add tags in the front matter, they just doesn't appear in the website, please fix

**Comment by kimberlynete** [comment]
which website do you mean?Von meinem iPhone gesendet

> Am 04.07.2021 um 08:06 schrieb gramythedj ***@***.***>:
> 
> though we can add tags in the front matter, they just doesn't appear in the website, please fix

**Comment by gramythedj** [comment]
I mean when I use this Google/High performance template, when I write a
blog post  using this template, tags are not appearing after , I publish
the blog post, not even near the footer

**Comment by kimberlynete** [comment]
is an ex friend of mine who does that.  don't want to have anything to do there please  take them out of memeinem iPhone gesendet

> Am 04.07.2021 um 14:40 schrieb gramythedj ***@***.***>:
> 
> I mean when I use this Google/High performance template, when I write a
> blog post using this template, tags are not appearing after , I publish
> the blog post, not even near the footer
