### ISSUE TITLE
AMP issues

### ISSUE THREAD

**Issue by jakefuller1** [google/eleventy-high-performance-blog#92]
for amp pages ...
only the files jpg create a scrset

**Comment by cramforce** [comment]
AMP doesn't support the picture element, hence only a jpeg srcset is generated. In theory the media attribute could be used to generate N amp-img element and only show one of them, but I'd rather wait for picture element support in AMP. 

Does that address your problem?

**Comment by jakefuller1** [comment]
Yes lets wait for picture. I have both htm and amp. Prefer to keep "posts" same in both. Layouts is different.
Just added web vitals to (UA) amp-analytics
Thank you.
