### ISSUE TITLE
How to implement share counter?

### ISSUE THREAD

**Issue by mufidu** [google/eleventy-high-performance-blog#98]
Sorry if this is outside of the scope, but I'd like to know how to implement the share counter? We can find it in https://www.industrialemphaty.com but not in the [demo](https://eleventy-high-performance-blog-sample.industrialempathy.com/). 

I saw in the dev console that it sends requests to Netlify GA function. Do we need to use Google Analytics to have the counter?

Thanks.

**Comment by cramforce** [comment]
On my side the share counter is backed by Twitter API calls which commit their response to the repo on a cron job and then do a static generation. The GA call via netlify is unrelated.

There would be many other ways of doing it. Definitely out of scope for this project.
